env:
  browser: true
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
extends:
  - "eslint:recommended"
  - './node_modules/gts'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules:
  # brace-style: ["error", "stroustrup"]
  camelcase: ["error"]
  no-tabs: ["error"]
  no-var: ["error"]
  prefer-const: ["error"]
  prefer-numeric-literals: ["error"]
  quotes: ["warn", "double"]
  eol-last: ["error"]
